services:
  node:
    build: ./
    working_dir: /app
    entrypoint: node
    volumes:
      - .:/app

  yarn:
    build: ./
    working_dir: /app
    entrypoint: yarn
    volumes:
      - .:/app

  npm:
    build: ./
    working_dir: /app
    entrypoint: npm
    volumes:
      - .:/app

  npx:
    build: ./
    working_dir: /app
    entrypoint: npx
    volumes:
      - .:/app

  next-app:
    build: ./
    working_dir: /app
    command: npm run dev
    ports:
      - "3003:3000"
    volumes:
      - .:/app

  next-app-prod:
    build: ./
    working_dir: /app
    command: npm run prod
    environment:
      NODE_ENV: production
      DATABASE_URL: "mysql://root:rootpassword@mariadb:3306/prompt_builder"
      NEXTAUTH_URL: http://127.0.0.1:3003
      NEXTAUTH_SECRET: aSuPerAnD0mStr1ng
    ports:
      - "3000:3000"
    volumes:
      - .:/app

  mariadb:
    platform: linux/amd64
    image: mariadb:10.5.8
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
    restart: "no"